[[constraint]]
  name = "github.com/Mongey/terraform-provider-kafka"
  branch = "cm-prefix-support"

[[constraint]]
  name = "github.com/Shopify/sarama"
  source = "github.com/Mongey/sarama"
  branch = "cm-v1-create-acl-request"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-hclog"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

